version: '3'

services:
    web:
        build: .
        image: mahesh1985/swarm-example:1.0
        ports:
            - 80:3000
        networks:
            - mynet
        deploy:
            replicas: 6
            update_config:
                parallelism: 2
                delay: 10s
    db:
        image: mongo:4.0.3
        networks: 
            - mynet
networks:
    mynet:
